#! /bin/sh


getcolors() {
	  FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	  BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	  BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	  RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	  GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	  YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	  BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	  MAGENTA=$(xrdb -query | grep 'color13:'| awk '{print $NF}')
	  CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	  WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors


# ----- CONFIG
bspc monitor -d '1' '2' '3' '4' '5' '6' '7' '8' '9' 

bspc config ignore_ewmh_focus true
bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "$GREEN" 
bspc config normal_border_color "$FOREGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$BLUE"




bspc config focus_follows_pointer         true
bspc config center_pseudo_tiled           true

bspc config pointer_modifier              mod4 
bspc config pointer_action1               move 
bspc config pointer_action2               resize_side 
bspc config pointer_action3               resize_corner

bspc config automatic_scheme              longest_side
bspc config initial_polarity              second_child

bspc config remove_disabled_monitors      true 
bspc config merge_overlapping_monitors    true

bspc config pointer_motion_interval       16



# ----- WINDOW RULES
bspc rule -a gnome-calculator state=floating



# ------ AUTOSTART
killall -9 xsettingsd sxhkd dunst xfce4-power-manager bspc 

sxhkd &
xsetroot -cursor_name left_ptr
xsetroot -gray
nitrogen --restore &

if [[ ! $(pidof eww) ]]
then
  eww open ewwbar && sleep 2
  xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" $(xdo id -n eww-bar) 
fi

lxsession &
thunar --daemon &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 75.00 &
setxkbmap -layout us -variant altgr-intl &
mpd &
mpDris2 &
picom -b &
